# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'XFBifJoke' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'AFNetworking'
pod 'MJExtension'
pod 'SDWebImage'
pod 'MJRefresh'

  # Pods for XFBifJoke

  target 'XFBifJokeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XFBifJokeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


